### ISSUE TITLE
doc pages broken

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool-MATLAB#208]
Looks like moving to WecOptTool-MATLAB name has broken our documentation pages. Feel free to involve @H0R5E if helpful.

**Comment by ssolson** [comment]
This is failing due to sphinx-versioning (see traceback below) or see full build failure [here](https://travis-ci.com/github/SNL-WaterPower/WecOptTool-MATLAB/jobs/514124222)

I believe reading the travis.yml file line 30 that we are using a custom version of sphinx-versioning from @H0R5E 's repository :
`- pip install https://github.com/H0R5E/sphinxcontrib-versioning/archive/v1.8.5_support.zip`

@H0R5E can you comment on if a modification needs to be made to the zip or if you believe your zip is now deprecated?

```
/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sphinx/util/nodes.py:94: FutureWarning: 
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  for classifier in reversed(node.parent.traverse(nodes.classifier)):
Exception occurred:
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sphinxcontrib/mat_directives.py", line 46, in run
    params = DocumenterBridge(self.env, reporter, documenter_options, lineno, self.state)
TypeError: __init__() takes 5 positional arguments but 6 were given
The full traceback has been saved in /tmp/sphinx-err-epza7ghi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-1:
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/python/3.6.7/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sphinxcontrib/versioning/sphinx_.py", line 230, in _read_config
    _build(argv, config, Versions(list()), current_name, False)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sphinxcontrib/versioning/sphinx_.py", line 215, in _build
    raise SphinxError
sphinx.errors.SphinxError
=> sphinx-build failed for branch/tag while reading config: <local>
=> Unable to read file, continuing with only CLI args.
=> Cloning gh-pages into temporary directory...
=> Failed to clone from remote repo URL.
=> Cloning into '.'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failure.
The command "sphinx-versioning push -abt -e .nojekyll -e README.md docs gh-pages ." exited with 1.
```

**Comment by H0R5E** [comment]
Hey @ssolson,

Although sphinx-versioning is failing, I don't think this is the root of the issue. Looks like there are other problems here:

1. Something is wrong with [sphinx-contrib/matlabdomain](https://github.com/sphinx-contrib/matlabdomain). I vaguely remember a similar version conflict cropping up with WEC-Sim. Not sure without a deeper dive.
2. Because the repository was renamed (or remade?), the encryption keys that are required for sphinx-versioning to push the changes have been removed or broken. They will need to be regenerated.
3. The path to the docs on the front page is now wrong. It should be https://snl-waterpower.github.io/WecOptTool-MATLAB

I'm happy to sort these issues out, just let me know.

T

**Comment by ryancoe** [comment]
Given that we are working on another track now, if an easy fix is not immediately obvious I would suggest that we build the documentation as a PDF and post it in the repo (or some other solution that may not be fancy, but gets the job done).

**Comment by H0R5E** [comment]
Well, the docs at https://snl-waterpower.github.io/WecOptTool-MATLAB are working, so you could just delete the travis files to stop the compilation and leave it as it is.

**Comment by ryancoe** [comment]
Ok. I think that might be fine. Need to make sure the links pointing from repo to docs and from docs to repo are correct.

**Comment by H0R5E** [comment]
You'd need to recompile it somehow if you wanted to change the online documentation. If you strip out the API documentation then you won't need sphinx-contrib/matlabdomain. It should compile locally without it and then the gh-pages branch can be overwritten manually with the updated docs (with the loss of the previous versions).
